name: mm
favicon: null
layout_spectrum: 0.5095
typography_spectrum: 0.55606
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7369465969968587
  lightness: 0.875
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
